In [20]:
import tensorflow as tf

In [21]:
o = tf.zeros([2,3],dtype=tf.int32)
o

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [22]:
i = tf.ones([2,3],dtype=tf.int32)
i

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]])>

In [23]:
r = tf.random.normal([4, 4], mean=50, stddev=40)
r

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[  6.7203293,  72.2377   ,  20.441198 , -10.505909 ],
       [105.67952  ,  93.93143  ,  36.10672  ,  58.523937 ],
       [ 28.00847  ,  38.37896  ,  40.946877 ,  20.848793 ],
       [-46.789154 ,  47.10486  ,  87.931625 , 101.25191  ]],
      dtype=float32)>

In [24]:
tf.config.list_physical_devices('GPU')

[]

In [25]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [26]:
import torch

if torch.cuda.is_available():
    device = torch.device("cuda")
    print(f"GPU: {torch.cuda.get_device_name(0)} is available. Using device: {device}")
else:
    device = torch.device("cpu")
    print("No GPU available. Using device: CPU")

# Create a random tensor on the specified device
x = torch.randn(5, 3, device=device)
print("Tensor on device:", x.device)


GPU: NVIDIA GeForce RTX 3050 Laptop GPU is available. Using device: cuda
Tensor on device: cuda:0
